#!/bin/sh
#
# Copyright (c) 2018 by Adequate Systems, LLC.  All Rights Reserved.
# See LICENSE.TXT   **** NO WARRANTY ****
#
# Resume Mochimo in Safe Mode after a brief pause
#
if test -z $1
then
  echo 'usage: sresume data_dir [parameter...]'
  exit 1
fi
if test ! -f mochimo
then
   echo "Please cd to binary directory: no mochimo found."
   exit 1
fi
if test ! -f dbackup.tgz
then
   echo "To use Safe Mode, dbackup.tgz must exist."
   echo "Create with: tar -cvzf dbackup.tgz d"
   exit 1
fi
if test ! -d $1/bc
then
   echo "no $1/bc directory!"
   exit 1
fi
echo You are about to resume Mochimo Safe Mode.
echo The $1 and $1/bc directories get reset from dbackup.tgz
echo if there is a restart.
echo Press ctrl-c to cancel or RETURN to continue...
read
trap "" 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
trap ""  24 25 26 27 28 29 30 31
trap "exit 0" term
cd $1
# We are in d/ now
echo copy mining address
cp ../maddr.dat .
cp ../coreip.lst .
while true
do
echo leave restored files in place
#../mochimo -x345678 -e -l -t1 -d  $2 $3 $4 $5 $6 $7 $8 $9
../mochimo -x345678 -e -p2094 -S $2 $3 $4 $5 $6 $7 $8 $9
if test $? -eq 0
then
   echo Resume paused system with ./sresume
   exit 0
fi
# move back to bin/ from bin/d/
cd ..
echo remove d/ tree...
rm -rf $1
tar -xvzf dbackup.tgz
# move into d/
cd $1
touch txq1.lck mq.lck
echo wait...
sleep 30
rm -f cblock.dat mblock.dat miner.tmp
# RESTART
done
